import Link from 'next/link'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider";
import Theme from '@/components/Theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
          <body className={inter.className}>
              <ThemeProvider
              attribute="class"
          defaultTheme="system"
          enableSystem
                  disableTransitionOnChange
        >
          <div className='fixed top-0 right-0 p-4'>
                  <Theme/>
          </div>
                {children}
        <footer></footer>
                  </ThemeProvider>
      </body>
    </html>
  )
}